### ISSUE TITLE
[update_notifier.py] IO error upon installation

### ISSUE THREAD

**Issue by squigglezworth** [weechat/scripts#211]
Several users have gotten this error when installing the script.

~~~~
16:05 ! python: unable to parse file "/home/squigz/.weechat/python/update_notifier.py"
16:07 python: stdout/stderr: Traceback (most recent call last):
16:07 python: stdout/stderr:   File "/home/squigz/.weechat/python/update_notifier.py", line 255, in <module>
16:07 python: stdout/stderr:     un_update_cache()
16:07 python: stdout/stderr:   File "/home/squigz/.weechat/python/update_notifier.py", line 169, in un_update_cache
16:07 python: stdout/stderr:     compare_version = get_info_ver("stable")
16:07 python: stdout/stderr:   File "/home/squigz/.weechat/python/update_notifier.py", line 205, in get_info_ver
16:07 python: stdout/stderr:     filecontents = file(full_file_name(info)).read().strip()
16:07 python: stdout/stderr: IOError: [Errno 2] No such file or directory: '/home/squigz/.weechat/update_notifier/stable'
16:07 ! python: unable to parse file "/home/squigz/.weechat/python/update_notifier.py~~~~

**Comment by finchd** [comment]
Same thing here,
WeeChat 1.7.1 weechat-1.7.1-3.1 (OpenSuSE Tumbleweed),
update_notifier.py 0.4.0, (new today
python ==  2.7.12

Installed from /script, tried to load from scripts buffer:
```
13:09 python: stdout/stderr: Traceback (most recent call last):
13:09 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 255, in <module>
13:09 python: stdout/stderr:     un_update_cache()
13:09 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 168, in un_update_cache
13:09 python: stdout/stderr:     compare_version_num = get_info_ver("stable_number")
13:09 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 205, in get_info_ver
13:09 python: stdout/stderr:     filecontents = file(full_file_name(info)).read().strip()
13:09 python: stdout/stderr: IOError: [Errno 2] No such file or directory: '/home/finchd/.weechat/update_notifier/stable_number'
13:09 =!= python: unable to parse file "/home/finchd/.weechat/python/autoload/update_notifier.py"
```

After manually made /home/finchd/.weechat/update_notifier/ dir, and creating the file with some text in it:
`$ echo "1.7.1" > /home/finchd/.weechat/update_notifier/stable_number`

```
13:10 python: stdout/stderr: Traceback (most recent call last):
13:10 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 255, in <module>
13:10 python: stdout/stderr:     un_update_cache()
13:10 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 169, in un_update_cache
13:10 python: stdout/stderr:     compare_version = get_info_ver("stable")
13:10 python: stdout/stderr:   File "/home/finchd/.weechat/python/autoload/update_notifier.py", line 205, in get_info_ver
13:10 python: stdout/stderr:     filecontents = file(full_file_name(info)).read().strip()
13:10 python: stdout/stderr: IOError: [Errno 2] No such file or directory: '/home/finchd/.weechat/update_notifier/stable'
```

**Comment by flashcode** [comment]
I'm fixing the script.
