### ISSUE TITLE
fish.py: 

### ISSUE THREAD

**Issue by h-0-s-h** [weechat/scripts#500]
## Script / WeeChat

- Name of script: fish.py
- Script version: 0.11
- WeeChat version: 3.6-dev

This bug has been reported to the script author? No, pinging via @freshprince now.
Response or reason: 
TBD.

## Bug summary
```
18:29 python: stdout/stderr (fish): Traceback (most recent call last):
18:29 python: stdout/stderr (fish):   File "/home/h-0-s-h/.local/share/weechat/python/autoload/fish.py", line 728, in fish_modifier_in_privmsg_cb
18:29 python: stdout/stderr (fish):     raise e
18:29 python: stdout/stderr (fish):   File "/home/h-0-s-h/.local/share/weechat/python/autoload/fish.py", line 713, in fish_modifier_in_privmsg_cb
18:29 python: stdout/stderr (fish):     clean = blowcrypt_unpack(match.group(5), b, key)
18:29 python: stdout/stderr (fish):   File "/home/h-0-s-h/.local/share/weechat/python/autoload/fish.py", line 303, in blowcrypt_unpack
18:29 python: stdout/stderr (fish):     raw = base64.b64decode(rest)
18:29 python: stdout/stderr (fish):   File "/usr/lib/python3.9/base64.py", line 87, in b64decode
18:29 python: stdout/stderr (fish):     return binascii.a2b_base64(s)
18:29 python: stdout/stderr (fish): binascii.Error: Incorrect padding
18:29 =!= python: error in function "fish_modifier_in_privmsg_cb"
```
## Steps to reproduce

1. Attempt to decrypt blowfish-cbc encrypted message/text that uses ASCII box characters [(https://en.wikipedia.org/wiki/Box-drawing_character#:~:text=WGL4%20character%20set.-,Box%20Drawing,-%5B1%5D%0AOfficial](https://en.wikipedia.org/wiki/Box-drawing_character#:~:text=WGL4%20character%20set.-,Box%20Drawing,-%5B1%5D%0AOfficial)
2. Blowfish key is 42 characters long (A-Za-z0-9.)

## Current behavior
Text is not decrypted, script correctly identifies as such:
```
18:29 O< Messages to/from SOMENETWORK/#OHHI are *not* encrypted.
18:29 <@XXXX> +OK *737d7ils0V/dDBWd3CVbllvPdldIfAZY5NFZV6/s5gkWtGlW3Jf1dncyULXiClGsekUOT1+075QQwKOBzcLlJnZqjPbXDs8fY/jJjcjx4EgJfENtVQWKuFkhQNNXn9ACqy3+SC2tYurW/Xx/U5aSShx1LJKEXJzwNO/zKTieOtL5EhA2o2fq+Ebo3LRP2jpi5eOhT+NffWMzdjGzDWylLro71o7SnTKEDEibpVQQ0JsZecT1U+9Cqadb3t3jhWkoSYLMchmcuu9fCmgHmdl/1rCUZ0MPPURbzXxRICABBVjxva2y0Q/HURDyBatH/SGlFOEpF1XUadhRxkcm40m0+2hAyTuzQCz7wvtXFkPFEar6s6QDGjTZzli5avW/Ria6stlk3oq9X3p47lXeTY2QanRdV8+ZJ/sgZ1gS/iujY9e7vUZcATySbCx17wE/uS
```
## Expected behavior
Decrypted text

## Suggested solutions
Not sure if binascii function can correctly convert ASCII box drawing characters?

**Comment by freshprince** [comment]
Hey. Thanks for the report. 

This happens because the message got truncated (maybe because it was too long) and is not correctly padded. Here's a small patch that adds padding to the message if it's not correctly padded but I don't know if the resulting plaintext would make any sense. Could you maybe give it a try, please?

```
diff --git a/fish.py b/fish.py
index f0219df..b5cc8a0 100644
--- a/fish.py
+++ b/fish.py
@@ -301,6 +301,8 @@ def blowcrypt_unpack(msg, cipher, key):

     if rest.startswith('*'):  # CBC mode
         rest = rest[1:]
+        if len(rest) % 4:
+            rest += '=' * (4 - len(rest) % 4)
         raw = base64.b64decode(rest)

         iv = raw[:8]
@@ -309,7 +311,7 @@ def blowcrypt_unpack(msg, cipher, key):
         cbcCipher = Crypto.Cipher.Blowfish.new(
                 key.encode('utf-8'), Crypto.Cipher.Blowfish.MODE_CBC, iv)

-        plain = cbcCipher.decrypt(raw)
+        plain = cbcCipher.decrypt(padto(raw, 8))

     else:

```
